/**
 * Created by ehog on 2017. 04. 22..
 */

export const countryNameData = {
  hu: {
    '--': 'Ismeretlen vagy nemzetközi',
    'ad': 'Andorra',
    'ae': 'Egyesült Arab Emírségek',
    'af': '﻿Afganisztán',
    'ag': 'Antigua és Barbuda',
    'ai': 'Anguilla',
    'al': 'Albánia',
    'am': 'Örményország',
    'an': 'Ex. Holland Antillák',
    'ao': 'Angola',
    'aq': 'Antarktisz',
    'ar': 'Argentína',
    'as': 'Amerikai Szamoa ',
    'at': 'Ausztria',
    'au': 'Ausztrália',
    'aw': 'Aruba',
    'ax': 'Åland (Finn)',
    'az': 'Azerbajdzsán',
    'ba': 'Bosznia-Hercegovina',
    'bb': 'Barbados',
    'bd': 'Banglades',
    'be': 'Belgium',
    'bf': 'Burkina Faso',
    'bg': 'Bulgária',
    'bh': 'Bahrein',
    'bi': 'Burundi',
    'bj': 'Benin',
    'bl': 'Saint Barthelemy',
    'bm': 'Bermuda ',
    'bn': 'Brunei',
    'bo': 'Bolívia',
    'bq': 'Bonaire, Sint Eustatius, és Saba',
    'br': 'Brazília',
    'bs': 'Bahama-szigetek',
    'bt': 'Bhután',
    'bv': 'Bouvet-sziget',
    'bw': 'Botswana',
    'by': 'Belarusz',
    'bz': 'Belize',
    'ca': 'Kanada',
    'cc': 'Kókusz-szigetek/Keeling-szigetek',
    'cd': 'Kongói Demokratikus Köztársaság',
    'cf': 'Közép-afrikai Köztársaság',
    'cg': 'Kongó',
    'ch': 'Svájc',
    'ci': 'Elefántcsontpart',
    'ck': 'Cook-szigetek',
    'cl': 'Chile',
    'cm': 'Kamerun',
    'cn': 'Kínai Népköztársaság',
    'co': 'Kolumbia',
    'cp': 'Clipperton-sziget',
    'cr': 'Costa Rica',
    'cu': 'Kuba',
    'cv': 'Zöld-foki-szigetek',
    'cw': 'Curaçao',
    'cx': 'Karácsony-sziget',
    'cy': 'Ciprus',
    'cz': 'Csehország',
    'de': 'Németország',
    'dj': 'Dzsibuti',
    'dk': 'Dánia',
    'dm': 'Dominika',
    'do': 'Dominikai Köztársaság',
    'dz': 'Algéria',
    'ec': 'Ecuador',
    'ee': 'Észtország',
    'eg': 'Egyiptom',
    'eh': 'Nyugat-Szahara',
    'er': 'Eritrea',
    'es': 'Spanyolország',
    'et': 'Etiópia',
    'fi': 'Finnország',
    'fj': 'Fidzsi-szigetek',
    'fk': 'Falkland-szigetek',
    'fm': 'Mikronézia',
    'fo': 'Feröer szigetek ',
    'fr': 'Franciaország',
    'ga': 'Gabon',
    'gb': 'Egyesült Királyság',
    'gd': 'Grenada',
    'ge': 'Grúzia',
    'gf': 'Francia Guyana',
    'gg': 'Guernsey',
    'gh': 'Ghána',
    'gi': 'Gibraltár',
    'gl': 'Grönland',
    'gm': 'Gambia',
    'gn': 'Guinea',
    'gp': 'Guadeloupe',
    'gq': 'Egyenlítői-Guinea',
    'gr': 'Görögország',
    'gs': 'Dél-Georgia és Déli-Sandwich-szigetek',
    'gt': 'Guatemala',
    'gu': 'Guam',
    'gw': 'Bissau-Guinea',
    'gy': 'Guyana',
    'hk': 'Hongkong',
    'hm': 'Heard-sziget és McDonald-szigetek',
    'hn': 'Honduras',
    'hr': 'Horvátország',
    'ht': 'Haiti',
    'hu': 'Magyarország',
    'id': 'Indonézia',
    'ie': 'Írország',
    'il': 'Izrael',
    'im': 'Man',
    'in': 'India',
    'io': 'Brit Indiai-óceáni Terület',
    'iq': 'Irak',
    'ir': 'Irán',
    'is': 'Izland',
    'it': 'Olaszország',
    'je': 'Jersey',
    'jm': 'Jamaica',
    'jo': 'Jordánia',
    'jp': 'Japán',
    'ke': 'Kenya',
    'kg': 'Kirgizisztán',
    'kh': 'Kambodzsa',
    'ki': 'Kiribati',
    'km': 'Comore-szigetek',
    'kn': 'Saint Kitts és Nevis',
    'kp': 'Észak-Korea',
    'kr': 'Dél-Korea',
    'kw': 'Kuvait',
    'ky': 'Kajmán-szigetek',
    'kz': 'Kazahsztán',
    'la': 'Laosz',
    'lb': 'Libanon',
    'lc': 'Saint Lucia',
    'li': 'Liechtenstein',
    'lk': 'Srí Lanka',
    'lr': 'Libéria',
    'ls': 'Lesotho',
    'lt': 'Litvánia',
    'lu': 'Luxemburg',
    'lv': 'Lettország',
    'ly': 'Líbia',
    'ma': 'Marokkó',
    'mc': 'Monaco',
    'md': 'Moldova',
    'me': 'Montenegró',
    'mf': 'Saint Martin (Francia)',
    'mg': 'Madagaszkár',
    'mh': 'Marshall-szigetek',
    'mk': 'Macedónia',
    'ml': 'Mali',
    'mm': 'Mianmar',
    'mn': 'Mongólia',
    'mo': 'Makaó',
    'mp': 'Északi-Mariana-szigetek',
    'mq': 'Martinique',
    'mr': 'Mauritánia',
    'ms': 'Montserrat',
    'mt': 'Málta',
    'mu': 'Mauritius',
    'mv': 'Maldív-szigetek',
    'mw': 'Malawi',
    'mx': 'Mexikó',
    'my': 'Malajzia',
    'mz': 'Mozambik',
    'na': 'Namíbia',
    'nc': 'Új-Kaledónia',
    'ne': 'Niger',
    'nf': 'Norfolk-sziget',
    'ng': 'Nigéria',
    'ni': 'Nicaragua',
    'nl': 'Hollandia',
    'no': 'Norvégia',
    'np': 'Nepál',
    'nr': 'Nauru',
    'nu': 'Niue ',
    'nz': 'Új-Zéland',
    'om': 'Omán',
    'pa': 'Panama',
    'pe': 'Peru',
    'pf': 'Francia Polinézia',
    'pg': 'Pápua Új-Guinea',
    'ph': 'Fülöp-szigetek',
    'pk': 'Pakisztán',
    'pl': 'Lengyelország',
    'pm': 'Saint-Pierre és Miquelon',
    'pn': 'Pitcairn-szigetek',
    'pr': 'Puerto Rico ',
    'ps': 'Palesztina (Izraeli)',
    'pt': 'Portugália',
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Katar',
    're': 'Réunion ',
    'ro': 'Románia',
    'rs': 'Szerbia',
    'ru': 'Oroszország',
    'rw': 'Ruanda',
    'sa': 'Szaúd-Arábia',
    'sb': 'Salamon-szigetek',
    'sc': 'Seychelle-szigetek',
    'sd': 'Szudán',
    'se': 'Svédország',
    'sg': 'Szingapúr',
    'sh': 'Szent Ilona',
    'si': 'Szlovénia',
    'sj': 'Svalbard- és Jan Mayen-szigetek',
    'sk': 'Szlovákia',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Szenegál',
    'so': 'Szomália',
    'sr': 'Suriname',
    'ss': 'Dél-Szudán',
    'st': 'São Tomé és Príncipe',
    'sv': 'Salvador',
    'sx': 'Sint Maarten (Holland)',
    'sy': 'Szíria',
    'sz': 'Szváziföld',
    'tc': 'Turks- és Caicos-szigetek',
    'td': 'Csád',
    'tf': 'Francia Déli Területek',
    'tg': 'Togo',
    'th': 'Thaiföld',
    'tj': 'Tádzsikisztán',
    'tk': 'Tokelau-szigetek ',
    'tl': 'Kelet-Timor',
    'tm': 'Türkmenisztán',
    'tn': 'Tunézia',
    'to': 'Tonga',
    'tr': 'Törökország',
    'tt': 'Trinidad és Tobago',
    'tv': 'Tuvalu',
    'tw': 'Kínai Köztársaság',
    'tz': 'Tanzánia',
    'ua': 'Ukrajna',
    'ug': 'Uganda',
    'um': 'Az Amerikai Egyesült Államok Külső Szigetei',
    'us': 'Egyesült Államok',
    'uy': 'Uruguay',
    'uz': 'Üzbegisztán',
    'va': 'Klerikális Szentszék',
    'vc': 'Saint Vincent és a Grenadine-szigetek',
    've': 'Venezuela',
    'vg': 'Brit Virgin-szigetek',
    'vi': 'Amerikai Virgin-szigetek',
    'vn': 'Vietnam',
    'vu': 'Vanuatu',
    'wf': 'Wallis és Futuna',
    'ws': 'Szamoa',
    'xa': 'Abházia (Grúz)',
    'xc': 'Krím-félsziget (Ukrán)',
    'xk': 'Koszovó (Szerb)',
    'xn': 'Hegyi-Karabah / Arcak (Azeri)',
    'xo': 'Dél-Oszétia (Grúz)',
    'xq': 'Szomáliföld',
    'xt': 'Észak-Ciprus (Ciprusi)',
    'ye': 'Jemen',
    'yt': 'Mayotte',
    'za': 'Dél-Afrika',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
    'xx': 'Ismeretlen / Nemzetközi terület'
  }
};
